- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start frontend  container
  community.docker.docker_container:
    name: frontend
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
    state: started
    ports:
      # Publish container port 9000 as host port 8080
      - "8080:8080"
    env:
      CATALOGUE_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:CATALOGUE_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
      CATALOGUE_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:CATALOGUE_PORT token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      USER_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:USER_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      USER_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:USER_PORT token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      CART_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:CART_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      CART_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:CART_PORT token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      SHIPPING_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:SHIPPING_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      SHIPPING_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:SHIPPING_PORT token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      PAYMENT_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:PAYMENT_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      PAYMENT_PORT: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/{{app_name}}:PAYMENT_PORT token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"