- name: Setup the MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
    remote_src: yes

- name: Install MongoDB
  ansible.builtin.dnf:
    name: mongodb-org

- name: Replace old hostname with new hostname (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart the service to make the changes effected.
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: mongod