- name: Copy repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq-server
  ansible.builtin.dnf:
    name: rabbitmq-server

- name: Start rabbitmq-server
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: rabbitmq-server

- name: |-
    Add user to server and assign full access control on / vhost.
    The user might have permission rules for other vhost but you don't care.
  community.rabbitmq.rabbitmq_user:
    user: {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/payment:AMQP_USER token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}
    password: {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/payment:AMQP_PASS token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present