- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server

- name: Start MySQL Service.
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: mysqld

- name: Change the default root password in order to start using the database service
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/mysql:PASSWORD token={{ token }} url=http://vault-int.rdevopsb84.online:8200') }}