- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: common
    tasks_from: docker

- name: Start catalogue  container
  community.docker.docker_container:
    name: catalogue
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
    state: started
    ports:
      # Publish container port 9000 as host port 8080
      - "8080:8080"
    env:
      MONGO: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:MONGO token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
      MONGO_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:MONGO_URL token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"

- name: Catalogue requires master-data to be loaded.
  community.docker.docker_container:
    name: catalogue-schema
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
    state: started
    env:
      DB_TYPE: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:DB_TYPE token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      DB_HOST: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:DB_HOST token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      SCHEMA_FILE: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:SCHEMA_FILE token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"
      # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
      APP_GIT_URL: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{env}}/data/catalogue:APP_GIT_URL token={{ token }} url=http://vault-int.azdevopsb1.online:8200') }}"