- name: Install python
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: latest

- name: Include task list in play
  ansible.builtin.include_tasks:
    file: app_presetup.yaml

- name: Change the working directory to /app
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app