- name: Restart a container
  community.docker.docker_container:
    name: " { { role_name } }"
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
    state: started
    ports:
      # Publish container port 9000 as host port 8080
      - "8080:8080"
    env:
      CATALOGUE_HOST: "ssssh"
      # Values which might be parsed as numbers, booleans or other types by the YAML parser need to be quoted
      CATALOGUE_PORT: "yes"
      REDIS_HOST: ""