- name: Setup SystemD {{ app_name }} Service
  ansible.builtin.template:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Load the service.
  ansible.builtin.systemd_service:
    state: restarted
    enabled: true
    name: "{{ app_name }}"
    daemon_reload: true

