- name: Setup SystemD Catalogue Service
  ansible.builtin.copy:
    src: "{{ app_name }}.service"
    dest: /etc/systemd/system/catalogue.service

- name: Load the service.
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "{{ app_name }}"
    daemon_reload: true

